# Generated by Django 4.0.4 on 2022-04-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0003_rename_result_student_resultcs1_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='resultCS1_1',
            new_name='resultCS11',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultCS1_2',
            new_name='resultCS12',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultCS2_1',
            new_name='resultCS21',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultCS2_2',
            new_name='resultCS22',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultCS3_1',
            new_name='resultCS31',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultCS3_2',
            new_name='resultCS32',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultIT1_1',
            new_name='resultIT11',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultIT1_2',
            new_name='resultIT12',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultIT2_1',
            new_name='resultIT21',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultIT2_2',
            new_name='resultIT22',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultIT3_1',
            new_name='resultIT31',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resultIT3_2',
            new_name='resultIT32',
        ),
    ]
