# Generated by Django 4.0.4 on 2022-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0004_rename_resultcs1_1_student_resultcs11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
