# Generated by Django 4.0.4 on 2022-05-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0006_bscs1_1_bscs1_2_bscs2_1_bscs2_2_bscs3_1_bscs3_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bscs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bscs1_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bscs1_1')),
                ('bscs1_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bscs1_2')),
                ('bscs2_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bscs2_1')),
                ('bscs2_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bscs2_2')),
                ('bscs3_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bscs3_1')),
                ('bscs3_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bscs3_2')),
            ],
        ),
        migrations.CreateModel(
            name='Bsit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsit1_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bsit1_1')),
                ('bsit1_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bsit1_2')),
                ('bsit2_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bsit2_1')),
                ('bsit2_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bsit2_2')),
                ('bsit3_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bsit3_1')),
                ('bsit3_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bsit3_2')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bscs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bscs')),
                ('bsit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bsit')),
            ],
        ),
    ]
