# Generated by Django 4.0.4 on 2022-05-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0008_cs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retention_cs1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_count', models.TextField()),
            ],
        ),
    ]
