# Generated by Django 4.0.4 on 2022-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0009_retention_cs1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retention_cs2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_count', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Retention_cs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_count', models.TextField()),
            ],
        ),
    ]
