# Generated by Django 4.0.4 on 2022-05-06 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0010_retention_cs2_retention_cs3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsit',
            name='bsit1_1',
        ),
        migrations.RemoveField(
            model_name='bsit',
            name='bsit1_2',
        ),
        migrations.RemoveField(
            model_name='bsit',
            name='bsit2_1',
        ),
        migrations.RemoveField(
            model_name='bsit',
            name='bsit2_2',
        ),
        migrations.RemoveField(
            model_name='bsit',
            name='bsit3_1',
        ),
        migrations.RemoveField(
            model_name='bsit',
            name='bsit3_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='bscs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='bsit',
        ),
        migrations.AddField(
            model_name='bscs1_1',
            name='courseCS1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ics.cs'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bscs',
        ),
        migrations.DeleteModel(
            name='Bsit',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
