# Generated by Django 4.0.4 on 2022-05-06 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0011_remove_bsit_bsit1_1_remove_bsit_bsit1_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bscs1_1',
            name='courseCS1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.cs'),
        ),
    ]
