# Generated by Django 4.0.4 on 2022-05-06 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0012_alter_bscs1_1_coursecs1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bscs1_1',
            name='courseCS1',
        ),
        migrations.AddField(
            model_name='bscs1_1',
            name='courseCS',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cs',
            name='cs_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.bscs1_1'),
        ),
    ]
