# Generated by Django 4.0.4 on 2022-05-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0013_remove_bscs1_1_coursecs1_bscs1_1_coursecs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bscs1_1',
            name='courseCS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
