# Generated by Django 4.0.4 on 2022-05-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0015_alter_bscs1_1_coursecs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bscs1_1',
            name='courseCS',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
