# Generated by Django 4.0.4 on 2022-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0019_remove_bscs1_1_coursecs_bscs1_1_coursecs1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bscs1_1',
            name='courseCS1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
