# Generated by Django 4.0.4 on 2022-05-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0020_alter_bscs1_1_coursecs1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cs',
            old_name='cs_count',
            new_name='count',
        ),
    ]
