# Generated by Django 4.0.4 on 2022-05-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0021_rename_cs_count_cs_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cs',
            new_name='Course',
        ),
    ]
