# Generated by Django 4.0.4 on 2022-05-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0022_rename_cs_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Totalit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='count',
        ),
        migrations.AddField(
            model_name='course',
            name='countcs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.totalcs'),
        ),
        migrations.AddField(
            model_name='course',
            name='countit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ics.totalit'),
        ),
    ]
