# Generated by Django 4.0.4 on 2022-05-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0023_totalcs_totalit_remove_course_count_course_countcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='countcs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='countit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
