# Generated by Django 4.0.4 on 2022-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0024_alter_course_countcs_alter_course_countit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcs',
            name='cs',
        ),
        migrations.RemoveField(
            model_name='totalit',
            name='it',
        ),
        migrations.AddField(
            model_name='totalcs',
            name='totalcs',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalit',
            name='totalit',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
