# Generated by Django 4.0.4 on 2022-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0025_remove_totalcs_cs_remove_totalit_it_totalcs_totalcs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bscs1_1',
            name='courseCS1',
        ),
        migrations.AlterField(
            model_name='bscs1_1',
            name='idNumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
