# Generated by Django 4.0.4 on 2022-05-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0026_remove_bscs1_1_coursecs1_alter_bscs1_1_idnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retention_cs1',
        ),
        migrations.DeleteModel(
            name='Retention_cs2',
        ),
        migrations.DeleteModel(
            name='Retention_cs3',
        ),
    ]
