# Generated by Django 4.0.4 on 2022-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0027_delete_retention_cs1_delete_retention_cs2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bscs1_1',
            name='idNumber',
            field=models.CharField(max_length=15),
        ),
    ]
